Markdown linting
StackStorm/ansible-st2 pull request #307
Opened 2021-12-26 18:54 UTC by mamercad

Fixes #306; adding `markdownlint` to CI as well.

2021-12-29 19:25 UTC, armab requested changes
Thanks for the PR!

While the Markdown linting might look like a good enhancement at first, unlike `.yaml` linter where issues should be actionable or `.rst` linter for docs.stackstorm.com where the issue might lead to a broken template, or `ansible-lint` which is based on the best practices, Markdown linter provides just a little value while bringing lots of noise for a single README.md.

2021-12-29 22:09 UTC, mamercad commented on README.md
> +auto-remediation and many more.  Aka IFTTT orchestration for Ops.
Cool, I'll remove the CI and fix the problems in the README when I get a few.

2021-12-30 00:35 UTC, mamercad commented
Down to only line length warnings:

```bash
❯ mdl README.md 
README.md:51: MD013 Line length
README.md:53: MD013 Line length
README.md:54: MD013 Line length
README.md:55: MD013 Line length
README.md:56: MD013 Line length
README.md:57: MD013 Line length
README.md:59: MD013 Line length
README.md:60: MD013 Line length
README.md:61: MD013 Line length
README.md:63: MD013 Line length
README.md:64: MD013 Line length
README.md:65: MD013 Line length
README.md:66: MD013 Line length
README.md:67: MD013 Line length
README.md:69: MD013 Line length
README.md:70: MD013 Line length
README.md:71: MD013 Line length
README.md:72: MD013 Line length
README.md:74: MD013 Line length
README.md:75: MD013 Line length
README.md:76: MD013 Line length
README.md:77: MD013 Line length
README.md:78: MD013 Line length
README.md:79: MD013 Line length

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
```

2022-01-03 14:53 UTC, armab commented
Hi @mamercad, we don't enforce the line length limit for Markdown files.
Is there any specific issue you're having with rendering the README.md?
Please include those practical fixes and enhancements only.

To make the build green, you can update your working branch with the most recent upstream master.

2022-01-04 13:28 UTC, mamercad commented
> Hi @mamercad, we don't enforce the line length limit for Markdown files. Is there any specific issue you're having with rendering the README.md? Please include those practical fixes and enhancements only.
> 
> To make the build green, you can update your working branch with the most recent upstream master.

The linting problems were visual noise in my IDE, that's all. I'll rebase shortly.

2022-01-04 13:36 UTC, mamercad commented
If you'd like me to undo line length, just let me know.

2022-01-04 19:46 UTC, armab commented
@mamercad Yes, please.

2022-01-04 23:02 UTC, armab approved these changes
Thanks :+1:

2022-01-04 23:05 UTC, merged