Refresh the `README.md`
StackStorm/ansible-st2 pull request #327
Opened 2022-12-07 13:08 UTC by mamercad

Fix the broken Slack badge image, remove contractions, make grammar changes, write OS names and versions more consistently, etc.

2022-12-07 13:48 UTC, armab requested changes
I'm :+1:  for the Readme refresh, but :-1: for Markdown linting as that's another uneeded check that might block a PR or change.

I think markdown linting makes sense for the projects where every file is documentation, but not for a single `README.md` when the frequency of change is low and the chance of breaking a Markdown file is even lower (they just work!).
Let's avoid utilizing computing resources in this case :green_apple:

2022-12-07 13:57 UTC, mamercad commented
> > I'm 👍 for the Readme refresh, but 👎 for Markdown linting as that's another uneeded check that might block a PR or change.
> > I think markdown linting makes sense for the projects where every file is documentation, but not for a single `README.md` when the frequency of change is low and the chance of breaking a Markdown file is even lower (they just work!). Let's avoid utilizing computing resources in this case 🍏
> 
> Sure, I'll push without the workflow shortly.

Done, I rebased as well so the history should be clean.

2022-12-07 21:34 UTC, mamercad commented
In the spirit of not running workflows unnecessarily, I'm noticing that the `build` workflow is running (for this `README.md` update, we should probably fix that).

2022-12-08 12:30 UTC, armab commented on .github/workflows/build.yaml
> +      - README.md
Nice! :+1:

2022-12-08 12:31 UTC, armab approved these changes
Thanks for the refresh!

2022-12-08 12:31 UTC, merged